services:
  - type: web
    name: book-recommender
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONOPTIMIZE
        value: "2"
    plan: free
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: chroma-db
      mountPath: /app/chroma_db
      sizeGB: 1 